import {FooterLinks} from './footer-links.jsx';
import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {api,money,instagram,Field,Logo,Modal} from './shared.jsx';
import {CategoryCards,ProductCard,PhotoGallery,Reveal,imagesFor} from './gallery.jsx';
function Store(){
 const [products,setProducts]=useState([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[filter,setFilter]=useState('All'),[selected,setSelected]=useState(null),[panel,setPanel]=useState(null),[toast,setToast]=useState(''),[receipt,setReceipt]=useState(null);
 const [sort,setSort]=useState('featured');
 const [bag,setBag]=useState(()=>{try{const b=JSON.parse(localStorage.getItem('siaa-bag')||'[]');return Array.isArray(b)?b.filter(x=>typeof x.id==='string'&&typeof x.key==='string'&&typeof x.notes==='string'&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=20).slice(0,20):[];}catch{return [];}});
 const load=async()=>{setLoading(true);setLoadError('');try{const p=await api('/api/products');setProducts(p);setBag(b=>b.filter(x=>p.some(y=>x.id===y.id)));}catch(e){setLoadError(e.message);}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);useEffect(()=>{localStorage.setItem('siaa-bag',JSON.stringify(bag));},[bag]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);}},[toast]);
 function add(p,q,notes){if(bag.length>=20){setToast('Your bag can hold up to 20 requests.');return;}setBag([...bag,{key:crypto.randomUUID(),id:p.id,quantity:q,notes}]);setSelected(null);setToast('Added to your bag');}
 function chooseCategory(category){const update=()=>{setFilter(category);};if(document.startViewTransition&&!matchMedia('(prefers-reduced-motion: reduce)').matches)document.startViewTransition(update);else update();}
 const list=products.filter(p=>filter==='All'||p.category===filter);
 if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));
 if(sort==='photos')list.sort((a,b)=>imagesFor(b).length-imagesFor(a).length);
 return <><div className="topline studio-announcement"><span aria-hidden="true">✧</span> Made by hand. Given with love. <span aria-hidden="true">✧</span></div><header className="shop-header"><Logo/><nav aria-label="Main navigation"><a href="#collection">The collection</a><a href="#studio">Meet the studio</a><a href={instagram} target="_blank" rel="noopener">Instagram ↗</a></nav><button className="bag outline" onClick={()=>setPanel('bag')}><svg width="20" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M5 7h14l1 14H4L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/></svg>Your bag <span>{bag.reduce((n,x)=>n+x.quantity,0)}</span></button></header>
 <main><section className="hero"><div className="hero-copy"><span className="eyebrow">SKETCH • CRAFT • CREATE</span><h1>Little creations.<br/><em>Big feelings.</em></h1><p>Drawn with imagination. Crafted by hand.<br/>Discover a little piece of siaa’s creative world.</p><a className="button" href="#collection">Explore the collection</a><div className="hero-foot"><span className="heart">♡</span><span>For your favourite people.<br/>And a little something for you.</span></div></div><div className="hero-art"><div className="hero-mini mini-sketch"><img src="/assets/drawing-study.jpg" alt="Blue-haired character drawing by siaa"/><span>from the sketchbook</span></div><div className="photo-frame"><img src="/assets/bouquet.jpg" alt="siaa’s handmade blue pipe-cleaner flower bouquet" width="360" height="640"/><span>handmade, with a little heart ♡</span></div><div className="art-label">FROM SIAA’S STUDIO<br/><strong>Flowers, reimagined.</strong></div><span className="round-label">made<br/><em>by hand</em></span><div className="hero-mini mini-craft"><img src="/assets/duck-craft.jpg" alt="Handmade duck keychain by siaa"/><span>little joys, handmade</span></div></div></section>
 <div className="ribbon"><span>Sketches & drawings</span><i>✧</i><span>Handmade bouquets</span><i>✧</i><span>Little works of art</span><i>✧</i><span>Personal touches</span></div>
 <Reveal><CategoryCards products={products} onSelect={category=>{chooseCategory(category);document.getElementById('collection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}}/></Reveal>
 <section className="collection section" id="collection"><div className="section-heading"><div><span className="eyebrow">THE COLLECTION / MADE BY SIAA</span><h2>Find your little <em>favourite.</em></h2></div><p>Real pieces. Real photographs.<br/>A little glimpse of the studio, just for you.</p></div><div className="collection-toolbar"><div className="filters" role="group" aria-label="Filter collection">{[['All','All creations'],['Bouquets','Bouquets'],['Drawings','Sketches & drawings'],['Crafts','Handmade crafts']].map(([value,label])=><button key={value} className={filter===value?'active':''} aria-pressed={filter===value} onClick={()=>chooseCategory(value)}>{label}<span>{products.filter(p=>value==='All'||p.category===value).length}</span></button>)}</div></div><div className="collection-meta"><span aria-live="polite">{loading?'Opening the studio…':list.length+' pieces · '+list.reduce((n,p)=>n+imagesFor(p).length,0)+' photographs'}</span><label>Sort by <select aria-label="Sort collection" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Studio selection</option><option value="name">Name, A–Z</option><option value="photos">Most photos</option></select></label></div><div className="product-grid" key={filter} aria-busy={loading}>{loading?Array.from({length:4},(_,i)=><div className="product-skeleton" key={i} aria-hidden="true"><div/><span/><span/></div>):loadError?<div className="error"><p>{loadError}</p><button onClick={load}>Try again</button></div>:list.length?list.map(p=><ProductCard key={p.id} p={p} onSelect={setSelected}/>):<div className="collection-empty"><span>♡</span><h3>A little more exploring?</h3><p>No pieces in this category yet.</p><button className="outline" onClick={()=>chooseCategory('All')}>See all creations</button></div>}</div><p className="collection-note">Each photograph is from siaa’s Instagram. Prices, personal touches and availability are confirmed with the studio.</p></section>
 <section id="studio" className="studio section"><div className="studio-photo"><img src="/assets/sketch.jpg" alt="Character drawing in progress from siaa’s Instagram" loading="lazy" width="360" height="640"/><span>A peek inside the sketchbook</span></div><div><span className="eyebrow">HELLO, FROM SIAA ♡</span><h2>Art-ing my way<br/><em>through life.</em></h2><p>A world of character drawings, playful sketches and flowers made by hand. Explore the work, follow the process, and share an idea for a piece of your own.</p><a className="text-link" href={instagram} target="_blank" rel="noopener">Visit @siaa_sketchncraft__ ↗</a><div className="steps"><div><b>01 / Find a piece</b><p>Browse the collection and choose what speaks to you.</p></div><div><b>02 / Make a request</b><p>Add your ideas, quantity and delivery details.</p></div><div><b>03 / Confirm together</b><p>The studio confirms availability, pricing and delivery before your order is final.</p></div></div></div></section>
 <section className="contact section"><span className="eyebrow">LET’S CREATE SOMETHING PERSONAL</span><h2>Have a little idea?</h2><p>Start a conversation with siaa on Instagram.</p><a className="button" href={instagram} target="_blank" rel="noopener">Say hello on Instagram</a></section></main><footer><Logo/><p>Sketch • Craft • Create</p><FooterLinks/><small>Images and artwork from @siaa_sketchncraft__.</small></footer>
 {selected&&<Modal label="product details" onClose={()=>setSelected(null)}><Product p={selected} onAdd={add}/></Modal>}
 {panel&&<Modal label="your bag" onClose={()=>setPanel(null)}>{panel==='bag'?<><span className="eyebrow">A LITTLE SOMETHING SPECIAL</span><h2>Your bag</h2>{bag.length?<>{bag.map(x=>{const p=products.find(p=>p.id===x.id);if(!p)return null;return <div className="bag-line" key={x.key}><img src={p.image} alt=""/><div><b>{p.name}</b><p>{money(p)}</p>{x.notes&&<p>{x.notes}</p>}</div><div className="bag-actions"><button className="outline" aria-label={'Decrease '+p.name+' quantity'} onClick={()=>setBag(bag.map(i=>i.key===x.key?{...i,quantity:Math.max(1,i.quantity-1)}:i))}>−</button><span>{x.quantity}</span><button className="outline" aria-label={'Increase '+p.name+' quantity'} onClick={()=>setBag(bag.map(i=>i.key===x.key?{...i,quantity:Math.min(20,i.quantity+1)}:i))}>+</button><button className="outline" aria-label={'Remove '+p.name} onClick={()=>setBag(bag.filter(i=>i.key!==x.key))}>Remove</button></div></div>;})}<p className="total">Final price and delivery to be confirmed</p><p className="hint">Send a request to the studio. There is no payment at this step and your order is only confirmed after you agree on the details.</p><button disabled={loading||!!loadError} onClick={()=>setPanel('checkout')}>Continue to your details</button></>:<><p className="empty">Your bag is waiting for a little creativity.</p><button onClick={()=>setPanel(null)}>Keep exploring</button></>}</>:panel==='checkout'?<Checkout bag={bag} onBack={()=>setPanel('bag')} onSuccess={r=>{setReceipt(r);setBag([]);setPanel('success');}}/>:<div className="success"><span className="eyebrow">REQUEST RECEIVED</span><h2>Thank you, {receipt.name}.</h2><p>Your request <strong>{receipt.reference}</strong> is saved in the studio’s order inbox.</p><p>Keep this reference. The studio will contact you to confirm your pieces, pricing and delivery. Your request is not a confirmed or paid order.</p><a className="text-link" href={instagram} target="_blank" rel="noopener">Contact siaa on Instagram ↗</a><br/><button onClick={()=>setPanel(null)}>Continue exploring</button></div>}</Modal>}
 {toast&&<div className="toast" role="status">{toast}</div>}</>;
}
function Product({p,onAdd}){return <div className="detail-grid"><PhotoGallery p={p}/><div><span className="eyebrow">{p.category}</span><h2>{p.name}</h2><b>{money(p)}</b><p>{p.description}</p>{p.source&&<a className="text-link" href={p.source} target="_blank" rel="noopener">See the original Instagram post ↗</a>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onAdd(p,Number(f.get('quantity')),f.get('notes').trim());}}><Field label="Quantity"><input name="quantity" type="number" min="1" max="20" defaultValue="1" required/></Field><Field label="Your personal touches" hint="Colours, a name, a message, or an idea — optional."><textarea name="notes" maxLength="2000" placeholder="Tell us what you have in mind…"/></Field><button type="submit">Add to your bag</button><p className="hint">Customisation and availability are confirmed by the studio.</p></form></div></div>;}
function Checkout({bag,onBack,onSuccess}){const [key]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e){e.preventDefault();setBusy(true);setError('');const customer=Object.fromEntries(new FormData(e.currentTarget));try{const r=await api('/api/orders',{method:'POST',body:JSON.stringify({customer,items:bag.map(({id,quantity,notes})=>({id,quantity,notes})),idempotencyKey:key})});onSuccess({...r,name:customer.name.split(' ')[0]});}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><span className="eyebrow">REQUEST YOUR PIECES</span><h2>A few personal details.</h2><p className="hint">The studio will confirm the final price, availability and delivery with you. Nothing is charged online.</p><form onSubmit={submit}><div className="form-grid"><Field label="Full name"><input name="name" autoComplete="name" maxLength="100" required/></Field><Field label="Email address"><input name="email" type="email" autoComplete="email" maxLength="254" required/></Field><Field label="Phone number" hint="Optional"><input name="phone" type="tel" autoComplete="tel" maxLength="30"/></Field><Field label="Instagram handle" hint="Optional"><input name="instagram" maxLength="60" placeholder="@yourname"/></Field><Field label="Delivery address" className="full"><textarea name="address" autoComplete="street-address" maxLength="1000" required placeholder="House / apartment, street and area"/></Field>{[['city','City','address-level2',100],['region','State / region','address-level1',100],['postal','Postal code','postal-code',20],['country','Country','country-name',100]].map(([name,label,ac,max])=><Field label={label} key={name}><input name={name} autoComplete={ac} maxLength={max} required/></Field>)}<Field label="Anything else?" hint="Optional" className="full"><textarea name="notes" maxLength="2000" placeholder="A special occasion, timing preferences, or a note for the studio"/></Field></div><label className="check-label"><input name="consent" type="checkbox" required/><span>I agree that the studio may store these details to respond to and fulfil my request. I understand that pricing, delivery and availability need confirmation.</span></label><p className="hint">Your address and contact details are visible only to the studio administrator. Contact the studio on Instagram to request changes or deletion.</p>{error&&<p className="error" role="alert">{error}</p>}<button type="submit" disabled={busy}>{busy?'Sending your request…':'Send order request'}</button> <button type="button" className="outline" disabled={busy} onClick={onBack}>Back to bag</button></form></>;}
createRoot(document.getElementById('root')).render(<Store/>);


